name: Copy published files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /template/. # MUST END IN /. FOR DIRECTORY OR WEIRD FOLDER DUPLICATION HAPPENS
          dst_path: /template # name of output directory
          src_branch: main
          dst_branch: main
          dst_owner: galacticpolymath
          dst_repo_name: gp-catalog
          clean: true
          commit_message: Automated publishing commit
